type: pages
headline: Projects
size: small
info: "{{ page.images.count }} image(s)"
layout: list
template: project
empty: No albums yet
status: listed
image:
  # query: page.cover
  cover: true
  ratio: 16/9
