title: Site

icon: 🏠

columns:
  - width: 2/3
    sections:
      drafts:
        type: pages
        headline: Drafts
        status: draft

      project: sections/project

      unlisted:
        headline: Unlisted
        type: pages
        status: unlisted

  - width: 1/3
    sections:
      pages:
        type: pages
        create: default
        templates:
          - home
          - error
