title: Site

icon: 🏠

columns:
  - width: 2/3
    sections:
      drafts:
        type: pages
        headline: Drafts
        status: draft
        templates:
          - project-left
          - project-right

      project-left: sections/project-left

      project-right: sections/project-right

      unlisted:
        headline: Unlisted
        type: pages
        status: unlisted
        templates:
          - project-left
          - project-right

  - width: 1/3
    sections:
      pages:
        type: pages
        create: default
        templates:
          - home
          - error
